#/bin/sh

export MYSQL_HOST=${MYSQL_SERVICE_HOST:-${LIBRENMS_MYSQL_HOST:-"127.0.0.1"}}
export MYSQL_PORT=${MYSQL_SERVICE_PORT:-${LIBRENMS_MYSQL_PORT:-"3306"}}

export RRDCACHED_HOST=${RRDCACHED_SERVICE_HOST:-${LIBRENMS_RRDCACHED_HOST:-"127.0.0.1"}}
export RRDCACHED_PORT=${RRDCACHED_SERVICE_PORT:-${LIBRENMS_RRDCACHED_PORT:-"42217"}}
export RRDCACHED_ADDRESS=${RRDCACHED_HOST}:${RRDCACHED_PORT}

export MEMCACHED_HOST=${MEMCACHED_SERVICE_HOST:-${LIBRENMS_MEMCACHED_HOST:-"127.0.0.1"}}
export MEMCACHED_PORT=${MEMCACHED_SERVICE_PORT:-${LIBRENMS_MEMCACHED_PORT:-"11211"}}
export MEMCACHED_SERVERS=${MEMCACHED_HOST}:${MEMCACHED_PORT}

export REDIS_HOST=${REDIS_SERVICE_HOST:-${LIBRENMS_REDIS_HOST:-"127.0.0.1"}}
export REDIS_PORT=${REDIS_SERVICE_PORT:-${LIBRENMS_REDIS_PORT:-"6379"}}
export REDISCLI_AUTH=${LIBRENMS_REDIS_PASSWORD:-"unknown"}

